set SERVEROUTPUT ON
DECLARE
V_SNO LT_ACCOUNT.ACCNO%TYPE;
V_NAME VARCHAR(100);
BEGIN

V_SNO := '&Enter_Account_No';
SELECT CFNAME into V_NAME from LT_CLIENT 
  join LT_ACCOUNT on LT_CLIENT.CLIENTID = LT_ACCOUNT.CLIENTID
  where ACCNO=V_SNO;
DBMS_OUTPUT.PUT_LINE ('Account number '||V_SNO||' is Used by '||V_NAME||'.');
EXCEPTION
WHEN NO_DATA_FOUND THEN
 DBMS_OUTPUT.PUT_LINE ('NODATA   '||V_SNO);
end;

CREATE SEQUENCE LT_ID
 START WITH     10000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
set SERVEROUTPUT ON
Declare 
V_FNAME LT_CLIENT.CFNAME%TYPE;
V_LNAME LT_CLIENT.CLNAME%TYPE;
V_EMAIL LT_CLIENT.CEMAIL%TYPE;
begin

  V_FNAME := '&Enter_FIRST_name';
  V_LNAME := '&Enter_LAST_name';
  V_EMAIL := '&Enter_EMAIL_Address';
  insert into LT_CLIENT values(LT_ID.NEXTVAL,null,V_FNAME,V_LNAME,null,V_EMAIL,null);
  commit;
end;

set SERVEROUTPUT ON
Declare 
V_ID LT_CLIENT.CLIENTID%TYPE := 123;
V_AMOUNT_D LT_TRANSACTION.TXAMOUNT%TYPE;
V_AMOUNT_W LT_TRANSACTION.TXAMOUNT%TYPE;

begin
  V_ID := '&input_the_client_Id';
  select sum(TXAMOUNT) into V_AMOUNT_D from LT_TRANSACTION
    join LT_ACCOUNT on LT_TRANSACTION.ACCNO = LT_ACCOUNT.ACCNO
    join LT_CLIENT  on LT_CLIENT.CLIENTID = LT_ACCOUNT.CLIENTID
    where LT_TRANSACTION.TXTYPE = 'D' and LT_CLIENT.CLIENTID = V_ID;
  select sum(TXAMOUNT) into V_AMOUNT_W from LT_TRANSACTION
    join LT_ACCOUNT on LT_TRANSACTION.ACCNO = LT_ACCOUNT.ACCNO
    join LT_CLIENT  on LT_CLIENT.CLIENTID = LT_ACCOUNT.CLIENTID
    where LT_TRANSACTION.TXTYPE = 'W' and LT_CLIENT.CLIENTID = V_ID;
    DBMS_OUTPUT.PUT_LINE ('Balance is '|| V_AMOUNT_D-V_AMOUNT_W);
    
    
end;



    join LT_ACCOUNT on LT_TRANSACTION.ACCNO = LT_ACCOUNT.ACCNO
    join LT_CLIENT  on LT_CLIENT.CLIENTID = LT_ACCOUNT.CLIENTID